find_package(OpenSSL REQUIRED)

set(OPENSSL_LIBRARY openssl)
add_library(${OPENSSL_LIBRARY} UNKNOWN IMPORTED)
set_target_properties(${OPENSSL_LIBRARY} PROPERTIES
    "IMPORTED_LOCATION" "${OPENSSL_SSL_LIBRARY}"
    "IMPORTED_LINK_INTERFACE_LIBRARIES" "${CMAKE_THREAD_LIBS_INIT}"
    "INTERFACE_INCLUDE_DIRECTORIES" "${OPENSSL_INCLUDE_DIR}")

# os provided "sudo locate libcrypto.a"
set(CRYPTO_LIBRARY crypto)
add_library(${CRYPTO_LIBRARY} UNKNOWN IMPORTED)
set_target_properties(${CRYPTO_LIBRARY} PROPERTIES
    "IMPORTED_LOCATION" "${OPENSSL_CRYPTO_LIBRARY}"
    "IMPORTED_LINK_INTERFACE_LIBRARIES" "${CMAKE_THREAD_LIBS_INIT}"
    "INTERFACE_INCLUDE_DIRECTORIES" "${OPENSSL_INCLUDE_DIR}")
